// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.26.1
// source: warden.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Citadel_Watch_FullMethodName = "/warden.Citadel/Watch"
)

// CitadelClient is the client API for Citadel service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CitadelClient interface {
	// 메서드명: Watch
	// 클라이언트 요청: Report (stream 방식)
	// 서버 응답: Command
	Watch(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Report, Command], error)
}

type citadelClient struct {
	cc grpc.ClientConnInterface
}

func NewCitadelClient(cc grpc.ClientConnInterface) CitadelClient {
	return &citadelClient{cc}
}

func (c *citadelClient) Watch(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Report, Command], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Citadel_ServiceDesc.Streams[0], Citadel_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Report, Command]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Citadel_WatchClient = grpc.ClientStreamingClient[Report, Command]

// CitadelServer is the server API for Citadel service.
// All implementations must embed UnimplementedCitadelServer
// for forward compatibility.
type CitadelServer interface {
	// 메서드명: Watch
	// 클라이언트 요청: Report (stream 방식)
	// 서버 응답: Command
	Watch(grpc.ClientStreamingServer[Report, Command]) error
	mustEmbedUnimplementedCitadelServer()
}

// UnimplementedCitadelServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCitadelServer struct{}

func (UnimplementedCitadelServer) Watch(grpc.ClientStreamingServer[Report, Command]) error {
	return status.Error(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedCitadelServer) mustEmbedUnimplementedCitadelServer() {}
func (UnimplementedCitadelServer) testEmbeddedByValue()                 {}

// UnsafeCitadelServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CitadelServer will
// result in compilation errors.
type UnsafeCitadelServer interface {
	mustEmbedUnimplementedCitadelServer()
}

func RegisterCitadelServer(s grpc.ServiceRegistrar, srv CitadelServer) {
	// If the following call panics, it indicates UnimplementedCitadelServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Citadel_ServiceDesc, srv)
}

func _Citadel_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CitadelServer).Watch(&grpc.GenericServerStream[Report, Command]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Citadel_WatchServer = grpc.ClientStreamingServer[Report, Command]

// Citadel_ServiceDesc is the grpc.ServiceDesc for Citadel service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Citadel_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "warden.Citadel",
	HandlerType: (*CitadelServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _Citadel_Watch_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "warden.proto",
}
