// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.26.1
// source: warden.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Report struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	WardenId string                 `protobuf:"bytes,1,opt,name=warden_id,json=wardenId,proto3" json:"warden_id,omitempty"`
	// Host Resource
	CpuUsage float32 `protobuf:"fixed32,2,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	MemUsage float32 `protobuf:"fixed32,3,opt,name=mem_usage,json=memUsage,proto3" json:"mem_usage,omitempty"`
	// 가동 시간
	Uptime int64 `protobuf:"varint,4,opt,name=uptime,proto3" json:"uptime,omitempty"`
	// 정보 수집 시점
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Network (Bytes)
	NetSent uint64 `protobuf:"varint,6,opt,name=net_sent,json=netSent,proto3" json:"net_sent,omitempty"`
	NetRecv uint64 `protobuf:"varint,7,opt,name=net_recv,json=netRecv,proto3" json:"net_recv,omitempty"`
	// Disk Usage (%)
	DiskUsage     float32 `protobuf:"fixed32,8,opt,name=disk_usage,json=diskUsage,proto3" json:"disk_usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Report) Reset() {
	*x = Report{}
	mi := &file_warden_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Report) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Report) ProtoMessage() {}

func (x *Report) ProtoReflect() protoreflect.Message {
	mi := &file_warden_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Report.ProtoReflect.Descriptor instead.
func (*Report) Descriptor() ([]byte, []int) {
	return file_warden_proto_rawDescGZIP(), []int{0}
}

func (x *Report) GetWardenId() string {
	if x != nil {
		return x.WardenId
	}
	return ""
}

func (x *Report) GetCpuUsage() float32 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *Report) GetMemUsage() float32 {
	if x != nil {
		return x.MemUsage
	}
	return 0
}

func (x *Report) GetUptime() int64 {
	if x != nil {
		return x.Uptime
	}
	return 0
}

func (x *Report) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Report) GetNetSent() uint64 {
	if x != nil {
		return x.NetSent
	}
	return 0
}

func (x *Report) GetNetRecv() uint64 {
	if x != nil {
		return x.NetRecv
	}
	return 0
}

func (x *Report) GetDiskUsage() float32 {
	if x != nil {
		return x.DiskUsage
	}
	return 0
}

type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_warden_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_warden_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_warden_proto_rawDescGZIP(), []int{1}
}

func (x *Command) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

var File_warden_proto protoreflect.FileDescriptor

const file_warden_proto_rawDesc = "" +
	"\n" +
	"\fwarden.proto\x12\x06warden\x1a\x1fgoogle/protobuf/timestamp.proto\"\x86\x02\n" +
	"\x06Report\x12\x1b\n" +
	"\twarden_id\x18\x01 \x01(\tR\bwardenId\x12\x1b\n" +
	"\tcpu_usage\x18\x02 \x01(\x02R\bcpuUsage\x12\x1b\n" +
	"\tmem_usage\x18\x03 \x01(\x02R\bmemUsage\x12\x16\n" +
	"\x06uptime\x18\x04 \x01(\x03R\x06uptime\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x19\n" +
	"\bnet_sent\x18\x06 \x01(\x04R\anetSent\x12\x19\n" +
	"\bnet_recv\x18\a \x01(\x04R\anetRecv\x12\x1d\n" +
	"\n" +
	"disk_usage\x18\b \x01(\x02R\tdiskUsage\"!\n" +
	"\aCommand\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action25\n" +
	"\aCitadel\x12*\n" +
	"\x05Watch\x12\x0e.warden.Report\x1a\x0f.warden.Command(\x01B\x06Z\x04./pbb\x06proto3"

var (
	file_warden_proto_rawDescOnce sync.Once
	file_warden_proto_rawDescData []byte
)

func file_warden_proto_rawDescGZIP() []byte {
	file_warden_proto_rawDescOnce.Do(func() {
		file_warden_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_warden_proto_rawDesc), len(file_warden_proto_rawDesc)))
	})
	return file_warden_proto_rawDescData
}

var file_warden_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_warden_proto_goTypes = []any{
	(*Report)(nil),                // 0: warden.Report
	(*Command)(nil),               // 1: warden.Command
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_warden_proto_depIdxs = []int32{
	2, // 0: warden.Report.timestamp:type_name -> google.protobuf.Timestamp
	0, // 1: warden.Citadel.Watch:input_type -> warden.Report
	1, // 2: warden.Citadel.Watch:output_type -> warden.Command
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_warden_proto_init() }
func file_warden_proto_init() {
	if File_warden_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_warden_proto_rawDesc), len(file_warden_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_warden_proto_goTypes,
		DependencyIndexes: file_warden_proto_depIdxs,
		MessageInfos:      file_warden_proto_msgTypes,
	}.Build()
	File_warden_proto = out.File
	file_warden_proto_goTypes = nil
	file_warden_proto_depIdxs = nil
}
